### ISSUE TITLE
C++ error with python 3.5

### ISSUE THREAD

**Issue by w4nderlust** [lyst/rpforest#18]
Hello,
I'm trying to fir an rpforet module on a big matrix (3000000 x 300) in python 3.5 on OS X 10.11 and I get the following error:

```
Traceback (most recent call last):
  File "rpforest_test.py", line 29, in <module>
    index.fit(model.syn0)
  File "/usr/local/lib/python3.5/site-packages/rpforest/rpforest.py", line 81, in fit
    tree.make_tree(self._X)
  File "rpforest/rpforest_fast.pyx", line 237, in rpforest.rpforest_fast.Tree.make_tree (rpforest/rpforest_fast.cpp:3896)
ValueError: Buffer dtype mismatch, expected 'double' but got 'float'
```

**Comment by iserko** [comment]
@w4nderlust not sure if you managed to fix this problem (after 3 and a half years), but the issue here is/was that you're using `np.float32` vs `np.float64` values in your vectors.

<img width="866" alt="Screenshot 2020-02-08 at 21 22 37" src="https://user-images.githubusercontent.com/473071/74092253-31046c00-4ab9-11ea-94e2-6f28b376ace6.png">

As soon as you ensure the vectors are float64 (aka double), then it works fine.

<img width="882" alt="Screenshot 2020-02-08 at 21 21 38" src="https://user-images.githubusercontent.com/473071/74092263-48435980-4ab9-11ea-9535-485447d43da3.png">

**Comment by w4nderlust** [comment]
Thanks!
